config/routes.rb
Tasker::Application.routes.draw do

  devise_for :users
  resources :projects do
    resources :tasks
  end

  match "projects/update" => "projects#update", :via => :post
  match "projects/create" => "projects#create", :via => :post
  match "/projects/:project_id/tasks/:id/edit" => "tasks#update", :via => :post
  match "/projects/:project_id/tasks/:id/toggle" => "tasks#toggle", :via => :post

  root :to => 'projects#index'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Project, user_id: user.id
    can :manage, Task, :project => { :user_id => user.id }
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
	attr_accessible :name
	has_many :tasks
	validates :name, :presence => true
  belongs_to :user
  validates_presence_of :user
end

app/models/task.rb
class Task < ActiveRecord::Base
   attr_accessible :name, :completed, :document, :document_file_name
   belongs_to :project
   validates :name, presence: true
   has_attached_file :document, :default_url => "/files/:style/missing.doc"
   validates_attachment_content_type :document, :content_type => /\Aapplication/
   validates_attachment_file_name :document, :matches => [/pdf\Z/, /doc\Z/]
  validates_attachment_size :document, :less_than=>1.megabyte
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation
  has_many :projects
  has_many :tasks, through: :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => "This is not your project"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
respond_to :html, :json, :xml
#load_and_authorize_resource :except => [:index, :show]
before_filter :authenticate_user!, :except => [:index, :show]
def index
   respond_with(@projects = Project.all)
   @project = Project.new
end

def show
    @project = Project.find(params[:id])
end

def new
  @project = Project.new
end

def create
    @project = Project.create(:name => params[:name])
    @project.user = User.find(session[:user_id]) if session[:user_id]
    authorize! :create, @project
    @project.save
    redirect_to projects_path
end

def edit
    @project = project.find(params[:id])
    authorize! :edit, @project
end

def update
  @project = Project.find(params[:id])
  @project.update(params[:project].permit(:name))
  authorize! :update, @project
  redirect_to projects_path
end

def destroy
  @project = Project.find(params[:id])
  authorize! :destroy, @project
  @project.destroy
  redirect_to projects_path
end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
#  load_and_authorize_resource :project
#  load_and_authorize_resource :task, :through => :project
	def index
   @tasks = @project.tasks.all
  end
  def create
    @project = Project.find(params[:project_id])
    authorize! :create, @project, @task
    @task = @project.tasks.create(params[:task].permit(:name, :completed, :document))
    redirect_to projects_path
  end
  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    @task.destroy
    redirect_to projects_path
  end
  def edit
   @project = Project.find(params[:project_id])
   @task = @project.tasks.find(params[:id])
 end

 def update
   @project = Project.find(params[:project_id])
   @task = @project.tasks.find(params[:id])
   @task.update(params[:task].permit(:name, :completed, :document))
   @task.document = params[:task][:document]
   redirect_to projects_path
  end
  
  def toggle
    @task = Task.find(params[:id])
    respond_to do |format|
      format.js do
        if (@task.completed != true)
          @task.completed = true
        else
          @task.completed = false
        end
        @task.save
        render :nothing => true
      end
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo lists</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=Ubuntu:400,500,700,500italic' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="wrapper">
   <h1><a href="/">Simple todo lists<span><br/>written in Rails 4 and making use of jQuery, AJAX,  SASS</span></a></h1>
 <% if notice %>
  <p class="alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert-danger"><%= alert %></p>
<% end %>
  <div class="userbar">
    <% if user_signed_in? %>
    Logged in as <%= current_user.email %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'register'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'register'  %><%= link_to "Login", new_user_session_path, :class => 'register'  %>
  <% end %>
  </div>
<%= yield %>
<div class="footer">
<p>&copy; <%= Time.now.year %> Valerie</p>
   </div>
<div id="mask" class="mask"></div>   
   </div>
  </body> 
</html>

app/views/projects/_form.html.erb
<%= form_for project, :html => { :id => "form_edit_project_#{project.id}", :class => "form_edit_project" } do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    <%= f.submit "Update list" %>
<% end %>

app/views/projects/edit.html.erb
<h3>Editing project</h3>
 
<%= render 'form' %>
 
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% @projects.each do |project| %>

  <%= div_for project do %>
  <h2><span><%= project.name %></span></h2>
<%= content_tag_for(:a, project, :edit, "href" => "#") do %>Edit list<% end %>
    <div class="popup">
    <a href="#" class="close">X</a>
      <%= render 'form', :project => project %>
    </div>
    <%= link_to 'Destroy', project_path(project), method: :delete, data: { confirm: 'Are you sure?'}, class: "delete-list" %>
     <% project.tasks.each do |task| %>
      <%= div_for task, class: (task.completed ? "done" : "open")  do %>
          <%= check_box_tag 'completed', task.id , task.completed, :class => "task-check" %>
          <span><p><%= task.name %></p></span>
      <% if task.document.exists? %>
        <%= link_to task.document.url, :class => 'file' do %><i class="fa fa-file-pdf-o"></i><%= task.document_file_name %><% end %>
          <% end %>
          <%= content_tag_for(:a, task, :edit, "href" => "#") do %>Edit task<% end %>
            <div class="popup">
            <a href="#" class="close">X</a>
              <%= render 'tasks/edit_task', :project => task.project, :task => task %>
            </div>
            <%= link_to 'Destroy Task', [task.project, task], method: :delete, data: { confirm: 'Are you sure?'}, class: 'delete-task' %>
<%= link_to "#", :id => "upload-for-#{task.id}", :class => "link-to-upload" do %><i class="fa fa-paperclip fa-lg"></i><% end %>
    <div class="popup file-upload">
    <a href="#" class="close">X</a>
    <%= render 'tasks/upload_file', :project => task.project, :task => task %>
     </div>
       <% end %><!--end div task -->
    <% end %><!--end task loop-->
    
  <%= form_for ([project, project.tasks.build]) do |f| %>
          <%= image_tag("green_plus.png") %>
          <%= f.text_field :name, :placeholder => "Start typing here to create a task...", :id => "new-task-name" %>
          <%= f.submit "Add task"%>
      <% end %><!-- end new task form -->
  <% end %><!-- end div project-->
 <% end %><!-- end project loop -->

<a href="#" class="new-list"><span>Add TODO list</span></a>
  <div class="popup" id="new_project">
  <a href="#" class="close">X</a>
  <%= form_tag("/projects/create", :method=>"post") do %>
  <%= label_tag("Name") %>
  <%= text_field_tag(:name) %>
    <%= submit_tag("Add TODO list") %>
  <% end %><!-- end project new-->
  </div>

app/views/projects/new.html.erb
<h1>New todo list</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/tasks/_edit_task.html.erb
<%= form_for [task.project, task], url: project_task_path(task.project, task), :html => { :id => "form_edit_task_#{task.id}", :class => "form_edit_task"} do |f| %>
            <%= f.label :name %><br>
            <%= f.text_field :name %>
            <%= f.submit "Update task" %>
<% end %>

app/views/tasks/_upload_file.html.erb
<%= form_for [task.project,task], :html => { :class => "upload-file", :id => "form-upload-for-#{task.id}" } do |upload|  %>
<%= upload.file_field :document %>
<%= upload.submit "Upload file" %>
<% end %>

app/views/tasks/edit.html.erb
<h3>Edit task</h3>
<%= form_for([@project, @project.tasks.build]) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>